let instagram={},all=[],filtered=[],shown=20,category='',occasion='',essentials=new Set(),region='',guests=0,maxPrice=0,withPrice=false,favs=new Set(JSON.parse(localStorage.getItem('makom-favs')||'[]'));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blob=p=>(p.amenities||[]).join(' ')+' '+(p.desc||''),has=(p,r)=>r.test(blob(p));
const rules={occasion:{couple:/זוג|רומנטי/,family:/משפח|ילדים/,birthday:/יום הולדת|יומולדת/,bachelor:/מסיבת רווקים|מסיבת רווקות/,group:/קבוצות|אירוע|מסיבות/},essential:{privatePool:/בריכה פרטית/,heatedPool:/בריכה מחוממת/,jacuzzi:/ג.?קוזי/,view:/נוף/,pets:/בעלי חיים|חיות מחמד/,accessible:/נגיש/,kosher:/דתי|כשר|בית כנסת/}};
const labels={couple:'חופשה זוגית',family:'חופשה משפחתית',birthday:'יום הולדת',bachelor:'מסיבת רווקים/ות',group:'אירוח קבוצה',privatePool:'בריכה פרטית',heatedPool:'בריכה מחוממת',jacuzzi:'ג׳קוזי',view:'נוף פתוח',pets:'חיות מחמד',accessible:'נגישות',kosher:'לשומרי מסורת'};
function image(p,i=0){return p.images?.[i]?`<img src="${esc(p.images[i])}" alt="${esc(p.name)}" loading="lazy" onerror="this.parentNode.innerHTML='<div class=noPhoto><i>⌂</i><span>התמונה תעלה בקרוב</span></div>'">`:`<div class="noPhoto"><i>⌂</i><span>התמונה תעלה בקרוב</span></div>`}
function init(){const regs=[...new Set(all.map(x=>x.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'he'));$('#region').innerHTML+=regs.map(x=>`<option>${esc(x)}</option>`).join('');$('#favCount').textContent=favs.size;bind();apply()}
function bind(){
 $('#q').addEventListener('input',()=>{shown=20;apply()});$('#searchBtn').onclick=()=>{$('.resultsSection').scrollIntoView({behavior:'smooth'});apply()};
 $$('.categoryCard').forEach(b=>b.onclick=()=>{$$('.categoryCard').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.category;shown=20;apply();$('.intent').scrollIntoView({behavior:'smooth',block:'center'})});
 $$('#occasionChips button').forEach(b=>b.onclick=()=>{let k=b.dataset.occasion;occasion=occasion===k?'':k;$$('#occasionChips button').forEach(x=>x.classList.toggle('active',x.dataset.occasion===occasion));shown=20;apply()});
 $$('#essentialChips button').forEach(b=>b.onclick=()=>{let k=b.dataset.essential;essentials.has(k)?essentials.delete(k):essentials.add(k);b.classList.toggle('active');shown=20;apply()});
 $('#region').onchange=e=>{region=e.target.value};$('#guests').onchange=e=>{guests=+e.target.value};$('#withPrice').onchange=e=>{withPrice=e.target.checked};
 $$('.priceOptions button').forEach(b=>b.onclick=()=>{$$('.priceOptions button').forEach(x=>x.classList.remove('active'));b.classList.add('active');maxPrice=+b.dataset.price});
 $('#sort').onchange=apply;$('#more').onclick=()=>{shown+=20;render()};
 const open=()=>{$('#filterDrawer').classList.add('open');$('#filterDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'},close=()=>{$('#filterDrawer').classList.remove('open');$('#filterDrawer').setAttribute('aria-hidden','true');document.body.style.overflow=''};
 $('#filterOpen').onclick=$('#openAllFilters').onclick=open;$('#filterClose').onclick=$('.drawerShade').onclick=close;$('#applyDrawer').onclick=()=>{shown=20;apply();close()};
 $('#clear').onclick=()=>{region='';guests=0;maxPrice=0;withPrice=false;category='';occasion='';essentials.clear();$('#region').value='';$('#guests').value='0';$('#withPrice').checked=false;$$('.priceOptions button').forEach((x,i)=>x.classList.toggle('active',i===0));$$('.categoryCard').forEach((x,i)=>x.classList.toggle('active',i===0));$$('.chipRow button').forEach(x=>x.classList.remove('active'));apply()};
 $('#detail .close').onclick=$('#detail .shade').onclick=closeDetail;document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDetail();close()}});
 $('#favBtn').onclick=()=>{if(!favs.size)return toast('עוד לא שמרתם מקומות');filtered=all.filter(x=>favs.has(x.id));shown=1000;render('המקומות ששמרתם')};
}
function apply(){let q=$('#q').value.trim().toLowerCase();filtered=all.filter(p=>(!q||[p.name,p.town,p.region,p.category,p.desc].join(' ').toLowerCase().includes(q))&&(!category||p.category===category||(category==='חאנים'&&has(p,/חאן/)))&&(!occasion||has(p,rules.occasion[occasion]))&&([...essentials].every(k=>has(p,rules.essential[k])))&&(!region||p.region===region)&&(!guests||p.guests>=guests)&&(!withPrice||p.priceMin)&&(!maxPrice||!p.priceMin||p.priceMin<=maxPrice));let sort=$('#sort').value;if(sort==='price')filtered.sort((a,b)=>(a.priceMin||1e9)-(b.priceMin||1e9));else if(sort==='rating')filtered.sort((a,b)=>(b.googleRating||0)-(a.googleRating||0)||(b.googleReviews||0)-(a.googleReviews||0));else filtered.sort((a,b)=>(b.images.length-a.images.length)||(b.googleRating||0)-(a.googleRating||0)||(b.desc.length-a.desc.length));render()}
function topTags(p){let out=[];if(has(p,/בריכה פרטית/))out.push('בריכה פרטית');else if(has(p,/בריכה/))out.push('בריכה');if(has(p,/ג.?קוזי/))out.push('ג׳קוזי');if(has(p,/נוף/))out.push('נוף');return out.slice(0,2)}
function render(title){$('#resultTitle').textContent=title||category||occasion&&labels[occasion]||($('#q').value?`תוצאות עבור “${$('#q').value}”`:'מקומות שכדאי להכיר');$('#count').textContent=`${filtered.length.toLocaleString('he-IL')} מקומות מתאימים`;let active=[];if(category)active.push(['category',category]);if(occasion)active.push(['occasion',labels[occasion]]);essentials.forEach(k=>active.push(['essential:'+k,labels[k]]));if(region)active.push(['region',region]);if(maxPrice)active.push(['price',`עד ₪${maxPrice.toLocaleString('he-IL')}`]);$('#activeFilters').innerHTML=active.map(([k,v])=>`<button data-remove="${k}">${esc(v)} ×</button>`).join('');$$('#activeFilters button').forEach(b=>b.onclick=()=>removeFilter(b.dataset.remove));
 $('#grid').innerHTML=filtered.slice(0,shown).map(p=>{let tags=topTags(p);return `<article class="card" data-id="${p.id}"><div class="photo">${image(p)}<button class="heart ${favs.has(p.id)?'saved':''}" aria-label="שמירה">${favs.has(p.id)?'♥':'♡'}</button>${p.book?'<span class="badge">אפשר להזמין אונליין</span>':''}</div><h3>${esc(p.name)}</h3><p class="meta">${esc([p.category,p.town,p.region].filter(Boolean).join(' · '))}</p><div class="cardTags">${tags.map(x=>`<span>${x}</span>`).join('')}</div><div class="cardline"><span class="rating">${p.googleRating?`<b>★</b> ${p.googleRating} <small>(${p.googleReviews||0})</small>`:p.guests?`עד ${p.guests} אורחים`:''}</span><span class="price">${p.priceMin?`החל מ־<strong>₪${p.priceMin.toLocaleString('he-IL')}</strong>`:'מחיר בפנייה'}</span></div></article>`}).join('');$$('.card').forEach(c=>c.onclick=e=>{let id=+c.dataset.id;if(e.target.closest('.heart')){toggleFav(id,e.target.closest('.heart'));e.stopPropagation()}else openDetail(id)});$('#more').style.display=shown<filtered.length?'block':'none'}
function removeFilter(k){if(k==='category'){category='';$$('.categoryCard').forEach((x,i)=>x.classList.toggle('active',i===0))}else if(k==='occasion'){occasion='';$$('#occasionChips button').forEach(x=>x.classList.remove('active'))}else if(k.startsWith('essential:')){let x=k.split(':')[1];essentials.delete(x);$(`[data-essential="${x}"]`)?.classList.remove('active')}else if(k==='region'){region='';$('#region').value=''}else if(k==='price'){maxPrice=0;$$('.priceOptions button').forEach((x,i)=>x.classList.toggle('active',i===0))}apply()}
function toggleFav(id,b){favs.has(id)?favs.delete(id):favs.add(id);localStorage.setItem('makom-favs',JSON.stringify([...favs]));b.classList.toggle('saved');b.textContent=favs.has(id)?'♥':'♡';$('#favCount').textContent=favs.size;toast(favs.has(id)?'נשמר לרשימה':'הוסר מהרשימה')}
function cleanPhone(s){return String(s||'').replace(/\D/g,'').replace(/^0/,'972')}
function openDetail(id){let p=all.find(x=>x.id===id),ig=instagram[id]||'',more=p.images.slice(1,3),map=p.lat&&p.lng?`<a class="mapLink" href="${esc(p.maps||'#')}" target="_blank" rel="noopener"><div class="cleanMap"><div class="mapgrid"></div><span class="pin">●</span><strong>${esc(p.town||p.region||'ישראל')}</strong><small>${p.lat.toFixed(3)}, ${p.lng.toFixed(3)} · פתיחה במפות</small></div></a>`:'';history.pushState({},'',`/property/${id}`);$('#detailBody').innerHTML=`<div class="gallery"><div class="photo">${image(p)}</div><div class="side">${more.map((_,i)=>`<div class="photo">${image(p,i+1)}</div>`).join('')}</div></div><div class="detailTop"><h1>${esc(p.name)}</h1><p class="detailMeta">${esc([p.category,p.town,p.region].filter(Boolean).join(' · '))}${p.guests?` · עד ${p.guests} אורחים`:''}${p.googleRating?` · ★ ${p.googleRating} ב-Google (${p.googleReviews||0} ביקורות)`:''}</p></div><div class="detailsplit"><div><h2>הסיפור של המקום</h2><p>${esc(p.desc||'מקום אירוח לחופשה ישראלית. פרטים נוספים זמינים בשיחה ישירה עם המארחים.')}</p>${p.amenities.length?`<h2>מה מחכה לכם</h2><div class="amenities">${p.amenities.slice(0,18).map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div>`:''}${map}</div><aside class="contact"><h3>${p.priceMin?`החל מ־₪${p.priceMin.toLocaleString('he-IL')} ללילה`:'לקבלת מחיר'}</h3><p>מדברים ישירות עם המקום, בלי מתווכים.</p>${p.phone?`<a href="tel:${cleanPhone(p.phone)}">להתקשר למקום</a>`:''}${p.whatsapp?`<a class="secondary" href="https://wa.me/${cleanPhone(p.whatsapp)}">WhatsApp</a>`:''}${p.website?`<a class="secondary" href="${esc(p.website)}" target="_blank" rel="noopener">האתר הרשמי</a>`:''}${ig?`<a class="secondary" href="${esc(ig)}" target="_blank" rel="noopener">Instagram</a>`:'<p class="igSoon">עמוד Instagram יתווסף אחרי אימות</p>'}<button class="secondary" onclick="navigator.share?navigator.share({title:'${esc(p.name)}',url:location.href}):navigator.clipboard.writeText(location.href)">שיתוף</button></aside></div>`;$('#detail').classList.add('open');$('#detail').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDetail(){if(!$('#detail').classList.contains('open'))return;$('#detail').classList.remove('open');$('#detail').setAttribute('aria-hidden','true');document.body.style.overflow='';if(location.pathname.startsWith('/property/'))history.pushState({},'','/')}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1700)}
Promise.all([fetch('/properties.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/instagram.json').then(r=>r.ok?r.json():{})]).then(([x,ig])=>{instagram=ig;all=x;let m=location.pathname.match(/\/property\/(\d+)/);init();if(m)openDetail(+m[1])}).catch(()=>{$('#count').textContent='לא הצלחנו לטעון את המקומות';});
