const { URL } = require('url');
const dns = require('dns').promises;
const net = require('net');
const crypto = require('crypto');
function privateIp(ip){if(!net.isIP(ip))return true;return /^(127\.|10\.|192\.168\.|169\.254\.|0\.|::1$|fc|fd|fe80)/i.test(ip)||(/^172\./.test(ip)&&(+ip.split('.')[1]>=16&&+ip.split('.')[1]<=31));}
async function safeUrl(raw){let u;try{u=new URL(raw)}catch{return null}if(u.protocol!=='https:'||u.username||u.password)return null;let a=await dns.lookup(u.hostname,{all:true});if(!a.length||a.some(x=>privateIp(x.address)))return null;return u}
function decode(s){return String(s||'').replace(/&amp;/g,'&').replace(/&#x2F;/gi,'/').replace(/&quot;/g,'"').trim()}
function imagesFromHtml(html,base){let out=[],seen=new Set(),rx=/(?:<img[^>]+(?:src|data-src|data-original)=["']([^"']+)|<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image)["'][^>]+content=["']([^"']+))/gi,m;while((m=rx.exec(html))){try{let u=new URL(decode(m[1]||m[2]),base);if(u.protocol==='https:'&&!seen.has(u.href)&&!/(logo|icon|sprite|pixel|avatar)/i.test(u.pathname)){seen.add(u.href);out.push(u.href)}}catch{}}return out.slice(0,30)}
function textFromHtml(html){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim().slice(0,12000)}
function signImage(propertyId,url){let secret=process.env.WEBSITE_MEDIA_SIGNING_SECRET||'';if(!secret)throw Error('website_media_not_configured');let body=Buffer.from(JSON.stringify({p:+propertyId,u:url})).toString('base64url');return body+'.'+crypto.createHmac('sha256',secret).update(body).digest('base64url')}
function verifyImage(token){let secret=process.env.WEBSITE_MEDIA_SIGNING_SECRET||'',parts=String(token||'').split('.');if(!secret||parts.length!==2)return null;let good=crypto.createHmac('sha256',secret).update(parts[0]).digest();let got;try{got=Buffer.from(parts[1],'base64url')}catch{return null}if(good.length!==got.length||!crypto.timingSafeEqual(good,got))return null;try{return JSON.parse(Buffer.from(parts[0],'base64url').toString())}catch{return null}}
async function fetchOfficialWebsite(property){let u=await safeUrl(property.website);if(!u)return null;let r=await fetch(u,{redirect:'follow',headers:{'User-Agent':'MakomTov/1.0 (+https://makom-tov.vercel.app)','Accept':'text/html,application/xhtml+xml'}});if(!r.ok||!String(r.headers.get('content-type')).includes('text/html'))return null;let final=await safeUrl(r.url);if(!final)return null;let html=(await r.text()).slice(0,1500000);let images=imagesFromHtml(html,final).map(x=>`/api/website-image?token=${encodeURIComponent(signImage(property.id,x))}`);return {sourceUrl:final.href,images,details:textFromHtml(html)} }
module.exports={fetchOfficialWebsite,verifyImage,safeUrl};
